import type { Metadata } from "next";
import TanstackProvider from "@/components/providers/tanstack-provider";
import "@ui/styles/globals.css";

export const metadata: Metadata = {
  title: "Stuffed",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body>
        <TanstackProvider>{children}</TanstackProvider>
      </body>
    </html>
  );
}
